# version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  mlflow:
    image: python:3.11-slim
    container_name: mlflow
    working_dir: /app
    volumes:
      - ./mlflow:/app
    command: >
      sh -c "pip install mlflow &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --allowed-hosts localhost:*,127.0.0.1:*"
    ports:
      - "5001:5000"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - "9000:9000"

  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow
    depends_on:
      - redis
      - mlflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow_home:/opt/airflow
      - ./src/pipelines:/opt/airflow/dags
      - ./:/opt/project
    ports:
      - "8080:8080"
    working_dir: /opt/project
    command: bash -c "airflow webserver --port 8080 & airflow scheduler"
  
  fraud-serving:
    image: ghcr.io/madhumitha282002/fraud_detection/fraud-serving:latest
    container_name: fraud-serving
    ports:
      - "8000:8000"
    restart: unless-stopped